name: Java CI with Maven and Node.js/Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        working-directory: ./e-shop-api
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: mvn -B compile

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        working-directory: ./e-shop-frontend
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  
