name: Java CI with Maven and Node.js/Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Change directory api
        run: mvn -B compile
        working-directory: ./e-shop-api

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Change directory frontend
        run: |
          npm ci
          npm run build --if-present
          npm test
        working-directory: ./e-shop-frontend
  
